server.port=443
server.ssl.enabled=true
server.context-path=/RightPrice-DAS
#server.error.whitelabel.enabled=false

## Syntel UAT Key
#server.ssl.key-store=classpath:samlkeytool.jks
#server.ssl.key-alias=samljksfile
#server.ssl.key-password=syntel123
#server.ssl.key-store-password=syntel123

##Evide UAT Key

#server.ssl.key-store=classpath:rptsteviden.jks
#server.ssl.key-alias=evidentstrp
#server.ssl.key-password=eviden123$
#server.ssl.key-store-password=eviden123$
#
#sso.tomcat.key-store=classpath:rptsteviden.jks
#sso.tomcat.key-alias=evidentstrp
#sso.tomcat.key-store-password=eviden123$

#sso.saml.idp.metadata=classpath:metadata/STG_cond2fa.xml
#security.saml2.metadata-url = https://dev-88456015.okta.com/app/exk15pgch2LhcpAnE5d7/sso/saml/metadata

########ATOS PROD
server.ssl.key-store=classpath:rpeviden.jks
server.ssl.key-alias=evidenprp
server.ssl.key-password=eviden123$
server.ssl.key-store-password=eviden123$



sso.tomcat.key-store=classpath:rpeviden.jks
sso.tomcat.key-alias=evidenprp
sso.tomcat.key-store-password=eviden123$

sso.saml.idp.metadata=classpath:metadata/Cond2FA_PRD.xml
#server.ssl.key-store=classpath:rpkeystoreprod.jks
#server.ssl.key-alias=atosrprod
#server.ssl.key-password=atos123$
#server.ssl.key-store-password=atos123$
#sso.tomcat.key-store=classpath:rpkeystoreprod.jks
#sso.tomcat.key-alias=atosrprod
#sso.tomcat.key-store-password=atos123$
##sso.saml.idp.metadata=classpath:metadata/wac.das.myatos.net-cond2fa_2020_10.xml
#sso.saml.idp.metadata=classpath:metadata/wac.das.myatos.net-cond2fa_2020_10.xml
#security.saml2.metadata-url = https://dev-88456015.okta.com/app/exk15pgch2LhcpAnE5d7/sso/saml/metadata
#server.session.cookie.max-age=10000
#server.session.timeout=5000

multipart.enabled=true
multipart.maxFileSize = 20Mb
multipart.maxRequestSize = 20Mb
spring.mvc.view.prefix: /
spring.mvc.view.suffix: .jsp
spring.messages.basename=validation



##Atos Prod  DB server details
spring.mysql.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.mysql.datasource.url=jdbc:sqlserver://SPCRPRPRDDB31:1433;DataBasename=RightPrice_PRD

spring.mysql.datasource.username=ENC(bLTxjxoPIFyHeEnht8Y3dg==)

spring.mysql.datasource.password=ENC(EQ4W7HF1SSw2XzNaFy/HX32cR6TzoMJrCU++8D9L1Hg=)


spring.mysql.datasource.maxactive=100
spring.mysql.datasource.maxidle=100
spring.mysql.datasource.minidle=50
spring.mysql.datasource.continue-on-error=true
spring.mysql.datasource.testWhileIdle=true
spring.mysql.datasource.testOnBorrow=true
spring.mysql.datasource.timeBetweenEvictionRunsMillis = 60000
spring.mysql.datasource.numTestsPerEvictionRun=3
spring.mysql.datasource.minEvictableIdleTimeMillis=600000
spring.mysql.datasource.validationQuery=SELECT 1
spring.mysql.datasource.tomcat.pool-size=1000
spring.mysql.datasource.tomcat.Initial-Size=50
spring.mysql.datasource.tomcat.max-wait=25000
spring.mysql.datasource.tomcat.max-active=100
spring.mysql.datasource.tomcat.max-idle=50
spring.mysql.datasource.tomcat.min-idle=50
spring.mysql.datasource.tomcat.validation-query= SELECT 1
spring.mysql.datasource.tomcat.test-on-borrow=true
spring.mysql.datasource.tomcat.test-on-connect=true
spring.mysql.datasource.tomcat.test-while-idle=true
spring.mysql.datasource.tomcat.log-abandoned=true
spring.mysql.datasource.tomcat.log-validation-errors=true


spring.jpa.properties.hibernate.dialect = com.rightprice.auth.config.CustomMsSqlDialect
spring.jpa.properties.hibernate.id.new_generator_mappings = false
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE




##spring.ds_mysql.testWhileIdle = true
##spring.ds_mysql.timeBetweenEvictionRunsMillis = 10000
##spring.ds_mysql.testonborrow=true
##spring.ds_mysql.validationQuery = SELECT 1
##spring.ds_mysql.tomcat.pool-size=200
##spring.ds_mysql.tomcat.Initial-Size=50
##spring.ds_mysql.tomcat.max-wait=20000
##spring.ds_mysql.tomcat.max-active=100
##spring.ds_mysql.tomcat.max-idle=50
##spring.ds_mysql.tomcat.min-idle=20


## Atos UAT DB-2 Server Details
spring.ds_mysql.url=jdbc:sqlserver://SPCRPRPRDDB31:1433;DataBasename=RightPrice_PRD
spring.ds_mysql.username=ENC(bLTxjxoPIFyHeEnht8Y3dg==)
spring.ds_mysql.password=ENC(EQ4W7HF1SSw2XzNaFy/HX32cR6TzoMJrCU++8D9L1Hg=)
spring.ds_mysql.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver



spring.ds_mysql.maxactive=100
spring.ds_mysql.maxidle=100
spring.ds_mysql.minidle=50
spring.ds_mysql.continue-on-error=true
spring.ds_mysql.testWhileIdle=true
spring.ds_mysql.testOnBorrow=true
spring.ds_mysql.timeBetweenEvictionRunsMillis = 60000
spring.ds_mysql.numTestsPerEvictionRun=3
spring.ds_mysql.minEvictableIdleTimeMillis=600000
spring.ds_mysql.validationQuery=SELECT 1
spring.ds_mysql.tomcat.pool-size=1000
spring.ds_mysql.tomcat.Initial-Size=50
spring.ds_mysql.tomcat.max-wait=25000
spring.ds_mysql.tomcat.max-active=100
spring.ds_mysql.tomcat.max-idle=50
spring.ds_mysql.tomcat.min-idle=50
spring.ds_mysql.tomcat.validation-query= SELECT 1
spring.ds_mysql.tomcat.test-on-borrow=true
spring.ds_mysql.tomcat.test-on-connect=true
spring.ds_mysql.tomcat.test-while-idle=true
spring.ds_mysql.tomcat.log-abandoned=true
spring.ds_mysql.tomcat.log-validation-errors=true




spring.ds_mssql.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.ds_mssql.url=jdbc:sqlserver://SPCRPRPRDDB31:1433;DataBasename=RightPrice_PRD
spring.ds_mssql.username=ENC(bLTxjxoPIFyHeEnht8Y3dg==)
spring.ds_mssql.password=ENC(EQ4W7HF1SSw2XzNaFy/HX32cR6TzoMJrCU++8D9L1Hg=)

spring.ds_mssql.maxactive=100
spring.ds_mssql.maxidle=100
spring.ds_mssql.minidle=50
spring.ds_mssql.continue-on-error=true
spring.ds_mssql.testWhileIdle=true
spring.ds_mssql.testOnBorrow=true
spring.ds_mssql.timeBetweenEvictionRunsMillis = 60000
spring.ds_mssql.numTestsPerEvictionRun=3
spring.ds_mssql.minEvictableIdleTimeMillis=600000
spring.ds_mssql.validationQuery=SELECT 1
spring.ds_mssql.tomcat.pool-size=1000
spring.ds_mssql.tomcat.Initial-Size=50
spring.ds_mssql.tomcat.max-wait=25000
spring.ds_mssql.tomcat.max-active=100
spring.ds_mssql.tomcat.max-idle=50
spring.ds_mssql.tomcat.min-idle=50
spring.ds_mssql.tomcat.validation-query= SELECT 1
spring.ds_mssql.tomcat.test-on-borrow=true
spring.ds_mssql.tomcat.test-on-connect=true
spring.ds_mssql.tomcat.test-while-idle=true
spring.ds_mssql.tomcat.log-abandoned=true
spring.ds_mssql.tomcat.log-validation-errors=true

logging.path=${catalina.home}/logs
logging.file=${logging.path}/RightPrice-DAS.log

jasypt.encryptor.password=RightPrice

spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate4.SpringSessionContext






